"""
Created on Fri Jul 26 07:12:28 2024
@author: obooklage
"""

import os
import uuid
from threading import Thread
import http.server
import glob

from urllib.parse import urlparse
from urllib.parse import parse_qs
import socketserver

server_path = '.'
pParent = None

class MyHttpRequestHandler(http.server.SimpleHTTPRequestHandler):
    uuid = uuid.uuid4()
    path = '.'
    global server_path

    def Initialize(self,path):
        self.path = path
        print(f"MyHttpRequestHandler {self.uuid} Initialize [{self.path}]")

    def do_GET(self):
        global server_path
        print(f"MyHttpRequestHandler {self.uuid} do_GET on [{server_path}]")
        self.send_response(200)
        self.send_header("Content-type", "text/html")
        self.end_headers()

        # Extract query param
        name = 'MIDIFILES'
        query_components = parse_qs(urlparse(self.path).query)
        if 'name' in query_components:
            name = query_components["name"][0]
            filepath = os.path.join(server_path,name)
            print(f"WebServer {self.uuid} request [{filepath}]")
            pParent.MidifileChange(filepath)

        midifiles = []
        for file in sorted(glob.glob(os.path.join(server_path,"*.mid"))):
            midifiles.append(os.path.basename(file))

        # Some custom HTML code, possibly generated by another function
        color = '#339933'
        header_style = f" style='color:{color};background-color:#333333;font-size: 32px;text-transform: uppercase;' "
        text_style = " style='font-size: 18px;' "
        html = f"<html><head></head><body><h1><span{header_style}>SELECT {name}</span></h1>"

        for midifile in midifiles:
            html += f"<span{text_style}><a href='?name={midifile}'>{midifile}</a></span><br>"

        html += "</body></html>"
        self.wfile.write(bytes(html, "utf8"))
        return

class ClassThreadWebServer(Thread):
    uuid = None
    midipath = None
    my_server = None
    port = 8888
    handler = None

    def __init__(self,Parent):
        global server_path
        global pParent
        Thread.__init__( self )
        pParent = Parent
        self.midipath = pParent.settings.GetMidiPath()
        server_path = pParent.settings.GetMidiPath()
        self.uuid = uuid.uuid4()
        self.handler = MyHttpRequestHandler
        self.handler.Initialize(self,pParent.settings.GetMidiPath())
        print(f"WebServer {self.uuid} port {self.port} serve [{server_path}]")

    def __del__(self):
        print(f"WebServer {self.uuid} destroyed")

    def run(self):
        PORT = 8888
        try:
            self.my_server = socketserver.TCPServer(("", PORT), self.handler)
            self.my_server.serve_forever()
        except:
            print(f"! WebServer {self.uuid} CAN NOT SERVE ON THIS PORT")

    def quit(self):
        if self.my_server:
            self.my_server.server_close()
            self.my_server.shutdown()


