[project]
name = "song-info-pyside"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.1",
    "mido>=1.3.3",
    "pyside6>=6.9.0",
]
